#############################################################################
# Makefile for building: FRDemo
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 2? 1 21:11:28 2018
# Project:  FRDemo.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile FRDemo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L../T3FaceClient -larcsoft_fsdk_face_tracking -larcsoft_fsdk_face_recognition -lxmnetsdk -larcsoft_fsdk_gender_estimation -larcsoft_fsdk_age_estimation -lmsc -lavcodec -lavutil -lswscale -lQtMultimedia -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		glhelper.cpp \
		camerasource.cpp \
		mainwidget.cpp \
		arcfaceengine.cpp \
		encoder.cpp \
		serialport.cpp \
		t3_face_network.cpp \
		t3_face_tts.cpp \
		t3_face_database.cpp moc_window.cpp \
		moc_camerasource.cpp \
		moc_mainwidget.cpp \
		moc_arcfaceengine.cpp \
		moc_encoder.cpp \
		moc_serialport.cpp \
		moc_t3_face_network.cpp \
		moc_t3_face_tts.cpp \
		qrc_t3_face_logo.cpp
OBJECTS       = main.o \
		window.o \
		glhelper.o \
		camerasource.o \
		mainwidget.o \
		arcfaceengine.o \
		encoder.o \
		serialport.o \
		t3_face_network.o \
		t3_face_tts.o \
		t3_face_database.o \
		moc_window.o \
		moc_camerasource.o \
		moc_mainwidget.o \
		moc_arcfaceengine.o \
		moc_encoder.o \
		moc_serialport.o \
		moc_t3_face_network.o \
		moc_t3_face_tts.o \
		qrc_t3_face_logo.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FRDemo.pro
QMAKE_TARGET  = FRDemo
DESTDIR       = 
TARGET        = FRDemo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FRDemo.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile FRDemo.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile FRDemo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FRDemo1.0.0 || $(MKDIR) .tmp/FRDemo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FRDemo1.0.0/ && $(COPY_FILE) --parents window.h glhelper.h camerasource.h mainwidget.h framesource.h arcfaceengine.h key.h arcsoft_fsdk_face_recognition.h arcsoft_fsdk_face_tracking.h netsdk.h encoder.h t3_log.h t3_library.h serialport.h arcsoft_fsdk_gender_estimation.h arcsoft_fsdk_age_estimation.h t3_face_network.h t3_face_tts.h msp_cmn.h msp_errors.h msp_types.h qtts.h t3_face_database.h .tmp/FRDemo1.0.0/ && $(COPY_FILE) --parents t3_face_logo.qrc .tmp/FRDemo1.0.0/ && $(COPY_FILE) --parents main.cpp window.cpp glhelper.cpp camerasource.cpp mainwidget.cpp arcfaceengine.cpp encoder.cpp serialport.cpp t3_face_network.cpp t3_face_tts.cpp t3_face_database.cpp .tmp/FRDemo1.0.0/ && (cd `dirname .tmp/FRDemo1.0.0` && $(TAR) FRDemo1.0.0.tar FRDemo1.0.0 && $(COMPRESS) FRDemo1.0.0.tar) && $(MOVE) `dirname .tmp/FRDemo1.0.0`/FRDemo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FRDemo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp moc_camerasource.cpp moc_mainwidget.cpp moc_arcfaceengine.cpp moc_encoder.cpp moc_serialport.cpp moc_t3_face_network.cpp moc_t3_face_tts.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_camerasource.cpp moc_mainwidget.cpp moc_arcfaceengine.cpp moc_encoder.cpp moc_serialport.cpp moc_t3_face_network.cpp moc_t3_face_tts.cpp
moc_window.cpp: arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		t3_face_database.h \
		t3_library.h \
		t3_face_network.h \
		window.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

moc_camerasource.cpp: framesource.h \
		camerasource.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) camerasource.h -o moc_camerasource.cpp

moc_mainwidget.cpp: arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		encoder.h \
		t3_library.h \
		t3_face_network.h \
		t3_face_database.h \
		mainwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_arcfaceengine.cpp: asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		arcfaceengine.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) arcfaceengine.h -o moc_arcfaceengine.cpp

moc_encoder.cpp: encoder.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) encoder.h -o moc_encoder.cpp

moc_serialport.cpp: t3_library.h \
		serialport.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) serialport.h -o moc_serialport.cpp

moc_t3_face_network.cpp: t3_face_network.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) t3_face_network.h -o moc_t3_face_network.cpp

moc_t3_face_tts.cpp: t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		t3_face_tts.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) t3_face_tts.h -o moc_t3_face_tts.cpp

compiler_rcc_make_all: qrc_t3_face_logo.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_t3_face_logo.cpp
qrc_t3_face_logo.cpp: t3_face_logo.qrc \
		bg/bg.jpg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name t3_face_logo t3_face_logo.qrc -o qrc_t3_face_logo.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp window.h \
		arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		t3_face_database.h \
		t3_library.h \
		t3_face_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp mainwidget.h \
		arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		encoder.h \
		t3_library.h \
		t3_face_network.h \
		t3_face_database.h \
		window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

glhelper.o: glhelper.cpp glhelper.h \
		asvloffscreen.h \
		amcomdef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glhelper.o glhelper.cpp

camerasource.o: camerasource.cpp camerasource.h \
		framesource.h \
		asvloffscreen.h \
		amcomdef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerasource.o camerasource.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		encoder.h \
		t3_library.h \
		t3_face_network.h \
		t3_face_database.h \
		camerasource.h \
		framesource.h \
		glhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

arcfaceengine.o: arcfaceengine.cpp arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h \
		arcsoft_fsdk_gender_estimation.h \
		key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arcfaceengine.o arcfaceengine.cpp

encoder.o: encoder.cpp encoder.h \
		t3_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encoder.o encoder.cpp

serialport.o: serialport.cpp serialport.h \
		t3_library.h \
		t3_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport.o serialport.cpp

t3_face_network.o: t3_face_network.cpp t3_face_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o t3_face_network.o t3_face_network.cpp

t3_face_tts.o: t3_face_tts.cpp t3_face_tts.h \
		t3_log.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o t3_face_tts.o t3_face_tts.cpp

t3_face_database.o: t3_face_database.cpp t3_face_database.h \
		t3_library.h \
		t3_log.h \
		arcfaceengine.h \
		asvloffscreen.h \
		amcomdef.h \
		arcsoft_fsdk_face_recognition.h \
		arcsoft_fsdk_face_tracking.h \
		arcsoft_fsdk_age_estimation.h \
		t3_face_tts.h \
		msp_cmn.h \
		msp_types.h \
		msp_errors.h \
		qtts.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o t3_face_database.o t3_face_database.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_camerasource.o: moc_camerasource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camerasource.o moc_camerasource.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_arcfaceengine.o: moc_arcfaceengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_arcfaceengine.o moc_arcfaceengine.cpp

moc_encoder.o: moc_encoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encoder.o moc_encoder.cpp

moc_serialport.o: moc_serialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport.o moc_serialport.cpp

moc_t3_face_network.o: moc_t3_face_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_t3_face_network.o moc_t3_face_network.cpp

moc_t3_face_tts.o: moc_t3_face_tts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_t3_face_tts.o moc_t3_face_tts.cpp

qrc_t3_face_logo.o: qrc_t3_face_logo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_t3_face_logo.o qrc_t3_face_logo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

